version: "3.7"
services:
  db:
    container_name: taicol-react-mysql
    ports:
      - "3306:3306"
    image: mysql:5.7
    restart: always
    environment:
      DATABASE_URL: mysql://root@localhost:3306/taicol
      MYSQL_DATABASE: taicol
      MYSQL_ALLOW_EMPTY_PASSWORD: "true"
    volumes:
      - ./db:/var/lib/mysql:rw
      - ./scripts/init.sql:/docker-entrypoint-initdb.d/init.sql:rw
    command:
      [
        "mysqld",
        "--character-set-server=utf8mb4",
        "--collation-server=utf8mb4_unicode_ci",
      ]
  app:
    links:
      - db
    depends_on:
      - db
    container_name: taicol-react-app
    restart: always
    ports:
      - "3000:3000"
    build:
      context: app
      dockerfile: Dockerfile
    volumes:
      - ./app:/app
      - /app/node_modules
